-- BlockTiers account + points administration setup
-- Run this in Supabase Dashboard -> SQL Editor.
--
-- IMPORTANT:
-- Your current account system already uses public.profiles.
-- This script adds the rankings/admin tables and policies.

-- =========================================================
-- EXISTING ACCOUNT TABLE
-- =========================================================

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    username text not null unique,
    display_name text not null,
    created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users can view their own profile"
on public.profiles for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create or replace function public.handle_new_blocktiers_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
    insert into public.profiles (id, username, display_name)
    values (
        new.id,
        new.raw_user_meta_data ->> 'username',
        new.raw_user_meta_data ->> 'display_name'
    );
    return new;
end;
$$;

drop trigger if exists on_auth_user_created_blocktiers on auth.users;
create trigger on_auth_user_created_blocktiers
after insert on auth.users
for each row execute procedure public.handle_new_blocktiers_user();

-- =========================================================
-- ADMIN ACCOUNTS
-- =========================================================

create table if not exists public.blocktiers_admins (
    user_id uuid primary key references auth.users(id) on delete cascade,
    created_at timestamptz not null default now()
);

alter table public.blocktiers_admins enable row level security;

-- Admin status is intentionally NOT readable/writable by normal users.
-- The website uses the security-definer function below.

create or replace function public.is_blocktiers_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.blocktiers_admins
        where user_id = auth.uid()
    );
$$;

revoke all on function public.is_blocktiers_admin() from public;
grant execute on function public.is_blocktiers_admin() to authenticated;

-- =========================================================
-- KIT RANKINGS
-- =========================================================

create table if not exists public.kit_rankings (
    id bigint generated by default as identity primary key,
    kit text not null check (kit in ('mace', 'sword', 'crystal', 'axe', 'uhc', 'smp')),
    username text not null,
    points integer not null default 0 check (points >= 0),
    created_at timestamptz not null default now()
);

alter table public.kit_rankings enable row level security;

drop policy if exists "Anyone can view BlockTiers rankings" on public.kit_rankings;
create policy "Anyone can view BlockTiers rankings"
on public.kit_rankings for select
to anon, authenticated
using (true);

drop policy if exists "Admins can update BlockTiers rankings" on public.kit_rankings;
create policy "Admins can update BlockTiers rankings"
on public.kit_rankings for update
to authenticated
using (public.is_blocktiers_admin())
with check (public.is_blocktiers_admin());

-- =========================================================
-- SECURE ADMIN UPDATE FUNCTION
-- =========================================================
-- The site calls this instead of relying only on a hidden button.

create or replace function public.update_blocktiers_points(
    p_id bigint,
    p_points integer
)
returns public.kit_rankings
language plpgsql
security definer
set search_path = public
as $$
declare
    updated_row public.kit_rankings;
begin
    if not public.is_blocktiers_admin() then
        raise exception 'Not authorized';
    end if;

    if p_points < 0 then
        raise exception 'Points cannot be negative';
    end if;

    update public.kit_rankings
    set points = p_points
    where id = p_id
    returning * into updated_row;

    if updated_row.id is null then
        raise exception 'Ranking entry not found';
    end if;

    return updated_row;
end;
$$;

revoke all on function public.update_blocktiers_points(bigint, integer) from public;
grant execute on function public.update_blocktiers_points(bigint, integer) to authenticated;

-- =========================================================
-- ADMIN SETUP
-- =========================================================
-- The current BlockTiers code uses RedaPlayz as the admin
-- username. If that is your account, run this after creating
-- the account. If your actual username is different, replace
-- RedaPlayz below with your exact username.
--
-- This does nothing if that username does not exist yet.

insert into public.blocktiers_admins (user_id)
select id
from public.profiles
where username = 'RedaPlayz'
on conflict (user_id) do nothing;

-- =========================================================
-- SEED THE CURRENT BLOCKTIERS RANKINGS
-- =========================================================
-- Only insert the current hard-coded entries if a kit has no
-- entries yet. This prevents duplicates when this script is run
-- more than once.

insert into public.kit_rankings (kit, username, points)
select *
from (
    values
        ('mace', 'Reda_TNT', 1700),
        ('mace', 'ITzMeArzhel', 0),
        ('mace', 'Nully', 1700),
        ('mace', 'user', 0),
        ('mace', 'User', 0),

        ('sword', 'Reda_TNT', 100),
        ('sword', 'ITzMeArzhel', 0),
        ('sword', 'User', 0),
        ('sword', 'User', 0),
        ('sword', 'User', 0),

        ('crystal', 'Reda_TNT', 50),
        ('crystal', 'ITzMeArzhel', 0),
        ('crystal', 'user', 0),
        ('crystal', 'user', 0),
        ('crystal', 'user', 0),

        ('axe', 'Reda_TNT', 0),
        ('axe', 'ITzMeArzhel', 0),
        ('axe', 'user', 0),
        ('axe', 'user', 0),
        ('axe', 'user', 0),

        ('uhc', 'Reda_TNT', 0),
        ('uhc', 'ITzMeArzhel', 0),
        ('uhc', 'user', 0),
        ('uhc', 'user', 0),
        ('uhc', 'user', 0),

        ('smp', 'Reda_TNT', 0),
        ('smp', 'ITzMeArzhel', 0),
        ('smp', 'user', 0),
        ('smp', 'user', 0),
        ('smp', 'user', 0)
) as seed(kit, username, points)
where not exists (
    select 1 from public.kit_rankings kr where kr.kit = seed.kit
);
